version: '2'

volumes:
  foodhub_mysql:
  foodhub_server:
  local:

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'ERLANGYODAWGHERESACOOKIE'
      RABBITMQ_DEFAULT_USER: 'urbanpiper'
      RABBITMQ_DEFAULT_PASS: 'urbanpiper'
      RABBITMQ_DEFAULT_VHOST: 'uphost'
    ports:
      - '15670:15672'
      - '5670:5672'

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: 'foodhub_db'
      MYSQL_ROOT_PASSWORD: 'Up123pU'
    volumes:
      - foodhub_mysql:/server/
      - .:/etc/mysql/conf.d/
      - local:/var/lib/mysql/
    ports:
      - '3300:3306'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server/image
    volumes:
      - foodhub_server:/server/
    stdin_open: true
    tty: true
    ports:
      - '8000:8000'
    entrypoint:
      - python3
      - manage.py
      - runserver
      - 0.0.0.0:8000
    depends_on:
      - mysql
      - rabbitmq

  celery:
    image: server/image
    entrypoint:
      - celery
      - -A
      - foodhub
      - worker

  celerybeat:
    image: server/image
    entrypoint:
      - celery
      - -A
      - foodhub
      - beat
